tf32_gemm_fwd:
    op: gemm
    args: --op gemm --only pt2_triton_matmul --m 1024 --n 512 --k 13469 --precision tf32 --metrics tflops --cudagraph --simple-output
    envs: TORCHINDUCTOR_COORDINATE_DESCENT_TUNING=1 TORCHINDUCTOR_MAX_AUTOTUNE_GEMM_SEARCH_SPACE=EXHAUSTIVE TORCHINDUCTOR_MAX_AUTOTUNE_GEMM=1 ENABLE_PERSISTENT_TMA_MATMUL=1 TRITON_ALWAYS_COMPILE=1 TORCHINDUCTOR_FORCE_DISABLE_CACHES=1
